---
Parameters:
  KeyName: # name of the parameter (keyname)
    Description: Select an existing keypair
    Type: AWS::EC2::KeyPair::KeyName
Mappings:
  RegionMap:
    ap-south-1:
      HVM64: ami-006d3995d3a6b963b
    ap-southeast-2:
      HVM64: ami-0300dc03c13eb7660
Resources:
  MyInstance: # 1 name of the resource
    Type: AWS::EC2::Instance
    DeletionPolicy: Retain
    Properties:
      AvailabilityZone: ap-south-1b
      ImageId: !FindInMap [RegionMap, !Ref AWS::Region, HVM64]
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      SecurityGroups:
        - !ImportValue GlobalSSHGroup
        - !Ref ServerSecurityGroup
      
      UserData: Fn::Base64: !Sub | #!/bin/bash apt-get update apt-get install apache2 -y systemctl start apache2 

  MyEIP: # 2 elastic ip for the instance
    Type: AWS::EC2::EIP
    DeletionPolicy: Retain
    Properties:
      InstanceId: !Ref MyInstance
  ServerSecurityGroup: # 4 http for the instance
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SG for port 80 and 8080
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0
